name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - django-version: "2.2"
            python-version: "3.8"
            grappelli: "1"
          - django-version: "3.2"
            python-version: "3.9"
          - django-version: "3.2"
            python-version: "3.10"
            grappelli: "1"
          - django-version: "4.2"
            python-version: "3.10"
          - django-version: "4.2"
            python-version: "3.11"
            grappelli: "1"
          - django-version: "5.1"
            python-version: "3.12"
          - django-version: "5.2"
            python-version: "3.12"
          - django-version: "5.2"
            python-version: "3.13"
            grappelli: "1"

    runs-on: ubuntu-latest
    name: Django ${{ matrix.django-version }} (Python ${{ matrix.python-version }})${{ matrix.grappelli == '1' && ' + grappelli' || '' }}
    env:
      PYTHON: ${{ matrix.python-version }}
      DJANGO: ${{ matrix.django-version }}
      GRAPPELLI: ${{ matrix.grappelli || '0' }}
      CHROME_HEADLESS: '1'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      run: |
       python3 -m pip install tox tox-gh-actions

    - name: Run tests
      run: |
        tox || tox || tox
